title: "Zhao Lingfeng's Website"
author: "Zhao Lingfeng"
email: "zhaolin46366@gmail.com"
description: "A Master's student specializing in pose estimation and LLM-based human activity recognition."
theme: minima

# 导航栏
navigation:
  - title: "About Me"
    url: /about
  - title: "Portfolio"
    url: /portfolio
  - title: "Contact Me"
    url: /contact

url: "https://zhao-lingfeng.github.io"
baseurl: ""
